.ruby: &ruby
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat *.gemspec
    populate_script: bundle update

remark_task:
  container:
    image: node:latest

  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - echo $CIRRUS_OS
      - node -v
      - cat package.json
    populate_script: npm install
  remark_script: npm run remark

rubocop_task:
  <<: *ruby

  container:
    image: ruby:latest

  rubocop_script: bundle exec rubocop

test_task:
  depends_on:
    - remark
    - rubocop

  <<: *ruby

  container:
    matrix:
      image: ruby:2.6
      image: ruby:2.7
      image: ruby:3.0
      image: ruby:3.1

  environment:
    CODECOV_TOKEN: ENCRYPTED[39c4ed9a5673bd7e9535a32b6acc788fa31e7b467f52e165c02c897f3e1f22ae59b1d2cb3659baa4bdb3f07d8356678c]

  test_script: bundle exec rspec
