bundle_cache: &bundle_cache
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat *.gemspec
  install_script:
    - gem update --system --no-document
    - bundle update

env:
  ## To suppress flood of warnings:
  ## https://github.com/cirruslabs/cirrus-ci-docs/issues/814
  ## https://github.com/rubygems/rubygems/issues/4466#issuecomment-818688569
  ## Global for:
  ## 1. different tasks (rubocop, test, etc.);
  ## 2. avoiding overriding `env` in specific cases like macOS.
  TMPDIR: $CIRRUS_WORKING_DIR

remark_task:
  container:
    image: node:latest

  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - echo $CIRRUS_OS
      - node -v
      - cat package.json
    populate_script: npm install
  remark_script: npm run remark

rubocop_task:
  container:
    image: ruby:latest

  <<: *bundle_cache

  rubocop_script: bundle exec rubocop

test_task:
  container:
    matrix:
      image: ruby:2.6
      image: ruby:2.7
      image: ruby:3.0
      image: ruby:3.1
      image: ruby:3.2

  environment:
    CODECOV_TOKEN: ENCRYPTED[39c4ed9a5673bd7e9535a32b6acc788fa31e7b467f52e165c02c897f3e1f22ae59b1d2cb3659baa4bdb3f07d8356678c]

  <<: *bundle_cache

  test_script: bundle exec rspec
